version: '3' # version of docker-compose
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports: # use '-' for an array
      - "8081:8081" # open up access to our container on our machine